version: '3.7'
services:
 db:
   image: mysql:5.7
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: 123
     MYSQL_DATABASE: db
     MYSQL_USER: prdenermatos
     MYSQL_PASSWORD: 321
   volumes:
     - db_data:/var/lib/mysql
   ports:
     - 3306:3306
volumes:
 db_data: {}
